apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-schema-service
  labels:
    app: generate-schema-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-schema-service
  template:
    metadata:
      labels:
        app: generate-schema-service
    spec:
      containers:
        - name: generate-schema-service
          image: verhovnick/generate-schema-service:v6
          ports:
            - containerPort: 82
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
