apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: cache-service
          image: verhovnick/cache-service:v5
          ports:
            - containerPort: 81
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
        - name: generate-schema-service
          image: verhovnick/generate-schema-service:v5
          ports:
            - containerPort: 82
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
        - name: request-validator-service
          image: verhovnick/request-validator-service:v6
          ports:
            - containerPort: 83
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
        - name: validation-service
          image: verhovnick/validation-service:v6
          ports:
            - containerPort: 84
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
