apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      name: cache-service
      port: 81
      targetPort: 8000
    - protocol: TCP
      name: generate-schema-service
      port: 82
      targetPort: 8001
    - protocol: TCP
      name: request-validator-service
      port: 83
      targetPort: 8002
    - protocol: TCP
      name: validation-service
      port: 84
      targetPort: 8003
  type: ClusterIP