apiVersion: v1
kind: Service
metadata:
  name: validation-service
  namespace: self-doc-project
spec:
  selector:
    app: validation
  ports:
    - protocol: TCP
      name: validation-service
      port: 84
      targetPort: 84
  type: ClusterIP