apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cache-service-ingress
  namespace: self-doc-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /cache-service
            pathType: Prefix
            backend:
              service:
                name: cache-service
                port:
                  number: 81
