apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: self-doc-project
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - "sh"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
