apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: self-doc-project
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      name: authentication-service
      port: 85
      targetPort: 85
  type: ClusterIP