apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: self-doc-project
spec:
  selector:
    app: cache
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: ClusterIP