apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: self-doc-project
data:
  MINIO_ACCESS_KEY: your-access-key
  MINIO_SECRET_KEY: your-secret-key

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: self-doc-project
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
          envFrom:
            - configMapRef:
                name: minio-config
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          platform: linux/amd/64
      volumes:
        - name: minio-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: self-doc-project
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
