
  apiVersion: v1
  kind: Service
  metadata:
    name: minio-service
    namespace: self-doc-project
  spec:
    type: NodePort
    selector:
      app: minio
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        nodePort: 30000  # Можно заменить на любое значение из диапазона NodePort