apiVersion: v1
kind: Service
metadata:
  name: request-validator-service
  namespace: self-doc-project
spec:
  selector:
    app: request-validator
  ports:
    - protocol: TCP
      name: request-validator-service
      port: 83
      targetPort: 83
  type: ClusterIP