apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: self-doc-project
spec:
  selector:
    app: storage
  ports:
    - protocol: TCP
      port: 86
      targetPort: 86
  type: ClusterIP